spring:
  application:
    name: spring-boot-camel
    description: Serviço Stateless
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
server:
  port: 8080
management:
  server:
    port: 9090