spring:
  application:
    name: spring-boot-service
    description: Serviço Stateless
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
server:
  port: 8081
management:
  server:
    port: 9091